### ISSUE TITLE
can i use this api with any ingeniamc drive?

### ISSUE THREAD

**Issue by roboticsai** [ingeniamc/ingenialink#3]
hello sir i'm really interested in you products. this days i'm searching for suitable motor drives which can be easily interfaced with linux system. i want to ask can i use this repository's package with any ingenialink drive systems?

**Comment by oriolbv** [comment]
Hi! Of course, you can use any Ingenia Motion Control drive with ingenialink libraries. 
Also, you can use  [ingenialink-python](https://github.com/ingeniamc/ingenialink-python) to communicate with our product in Python, instead of C.
Check our servo drives in [http://ingeniamc.com/products](http://ingeniamc.com/products).

Thank you 👍
